### ISSUE TITLE
Including specific emojis generator not working on macOS

### ISSUE THREAD

**Issue by bigblackclock** [bigblackclock/twemoji#12]
flutter pub run twemoji:include_emojis
Unhandled exception:
FileSystemException: Cannot open file, path = '/Users/hadi/Documents/package_config.json' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#4      main (file:///Users/hadi/Documents/dev/twemoji/bin/include_emojis.dart:21:46)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
pub finished with exit code 255

**Comment by bigblackclock** [comment]
@danReynolds could you take a look at it, please.

**Comment by danReynolds** [comment]
Yep looking

**Comment by amorenew** [comment]
```
➜  the_app flutter pub run twemoji:include_emojis
Unhandled exception:
FileSystemException: Directory listing failed, 
path = '/Users/apple/Side_Project/the_app/.dart_tool/pub/bin/assets/'
 (OS Error: No such file or directory, errno = 2)
Instance of '_StringStackTrace'pub finished with exit code 255
➜  the_app cd /Users/apple/Side_Project/the_app/.dart_tool/pub/bin/
➜  bin ls
all_assets twemoji
```

<img width="364" alt="Screen Shot 2022-11-14 at 4 50 29 PM" src="https://user-images.githubusercontent.com/2842459/201690567-fde85ed6-d699-42f7-bc1b-7201709df0ce.png">


@hadi-codes I have the same issue on macOS but I don't know the solution
