### ISSUE TITLE
Web support?

### ISSUE THREAD

**Issue by aytunch** [bigblackclock/twemoji#13]
Are you planning on supporting web?
Thanks

**Comment by bigblackclock** [comment]
it does work on the web.

**Comment by aytunch** [comment]
It does not show web as supported here: https://pub.dev/packages/twemoji

**Comment by bigblackclock** [comment]
it doesn't show up on pub. dev because I'm using the flutter_svg package.
on Flutter web CanvasKit renderer the emojis will show up as SVG and on the HTML render will show up as png :)

**Comment by aytunch** [comment]
@bigblackclock flutter_svg upgraded to v1.0.0 and now it supports web:
https://pub.dev/packages/flutter_svg
If you can update to the latest dependency maybe this package can show web as being supported?

**Comment by bigblackclock** [comment]
web is supported now
