### ISSUE TITLE
Numeric emoji symbols (0️⃣,1️⃣,..) are not converted to twitter emoji

### ISSUE THREAD

**Issue by Park-Wonbin** [bigblackclock/twemoji#5]
There is an issue on iOS that does not display numeric emoji. (https://github.com/flutter/flutter/issues/67723)
But, if you do `text.replaceAll('\u{fe0f}', '')`, the emoji comes out properly.

However, it is not displayed in the form of Twitter emoji. It just shows the device's default emoji.

Is there any solution?

**Comment by bigblackclock** [comment]
``text.replaceAll('\u{fe0f}', '')`` does this  works on all emojis ?

**Comment by Park-Wonbin** [comment]
I used `text.replaceAll('\u{fe0f}', '')` because of the numeric emoji encoding format on iOS.
https://emojipedia.org/keycap-digit-one/
If `U+FE0F` is erased, numeric emoji (1️⃣,2️⃣,3️⃣,..) are printed well.

There is no problem with other emojis. ex. 😊,🍎,..

ex. \u{0031}\u{20e3} → 1️⃣, \u{0031}\u{fe0f}\u{20e3} → 1□ (BUG ony iOS)

**Comment by Panimaster** [comment]
any update on this?

**Comment by hadi-codes** [comment]
fixed v0.4.3
